version: "2"

services:
  priva:
    build: ./deps/splatoon-privas
    volumes:
      - "./deps/splatoon-privas:/code"
    command: python /code/src/start_rpc.py
    expose:
      - 4242
    mem_limit: 128m
    restart: always
  bot:
    build: .
    volumes:
      - "./config.json:/code/config.json"
    depends_on:
      - priva
    command: npm run prod
    mem_limit: 150m
    restart: always
    environment:
      - CQ_HOST=${CQ_HOST}
      - CQ_ACCESS_TOKEN=${CQ_ACCESS_TOKEN}
      - TSBOT_ADMIN=${TSBOT_ADMIN}
      - QQAI_APPID=${QQAI_APPID}
      - QQAI_APPKEY=${QQAI_APPKEY}
      - BOT_DEBUG=true
      - PRIVA_HOST=${PRIVA_HOST}
      - DISABLE_SHARE=${DISABLE_SHARE}
